name: scallop_reactive_ble_platform_interface
description: Scallop-maintained fork of flutter_reactive_ble platform interface with downstream SDK and Flutter updates.
version: 6.0.1
homepage: https://github.com/fum-is-chum/flutter_reactive_ble
repository: https://github.com/fum-is-chum/flutter_reactive_ble
documentation: https://github.com/fum-is-chum/flutter_reactive_ble/tree/master/packages/reactive_ble_platform_interface

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  functional_data: ^1.0.0
  meta: ^1.7.0

  plugin_platform_interface: ^2.1.0

dev_dependencies:
  build_runner: ^2.4.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  functional_data_generator: ^1.1.2
  mockito: ^5.4.0

flutter:
